{{- range $i, $org := .Values.PeerOrgs }}

apiVersion: v1
kind: Service
metadata:
  name: hlf-ca--{{ $org.Name | lower }}
  labels:
    name: hlf-ca--{{ $org.Name | lower }}
spec:
  type: NodePort
  selector:
    app: hlf-ca--{{ $org.Name | lower }}
  ports:
  - protocol: TCP
    port: 7054
    name: http
    nodePort: 3170{{ $i | int }}
---
{{- end }} {{- /* Orgs */ -}}
